apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-sql-pv
  labels:
    type: local
  namespace: backend-ns
spec:
  storageClassName: local
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: backend-ns
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
