apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv
spec:
  storageClassName: redis-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data"
